image: python:3.8.5

pipelines:
  default:
    - parallel:
      - step:
          name: Django Company API tests
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest api/coronavstech -s -v --durations=0 --cov=.
      - step:
          name: Fibonacci tests
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest fibonacci/ -s -v --durations=0 --cov=.







